### ISSUE TITLE
Missing the start script in package.json

### ISSUE THREAD

**Issue by mohanadft** [expressots/expressots#102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior
I am trying to run the project, to make some contribution, but I have no clue about how to run the project.

> And run the project in development mode with:
> 
> ```bash
> npm start
> ```

Ok, sounds good, but when I open `package.json`, there is no start script. Any clue?
![image](https://github.com/expressots/expressots/assets/78538311/b8b4b37a-eb2f-415e-8cac-206d287b9d4e)

### Expected behavior

supposed to have the start script in `package.json`

### Package version

1.2.0

### Node.js version

19.8.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by rsaz** [comment]
Hi @mohanadft what package version is this? `1.2.0`? The current version of expressots/core is `2.1.0`

`@expressots/core` is a library, that being said there is nothing to run. You have to build the library, that will generate a `/lib` folder.

If you want to contribute to the project what I would recommend is firstly read the [Contributing Guide](https://github.com/expressots/expressots/blob/main/CONTRIBUTING.md).

Secondly scaffold a new project using the CLI `expressots new app-demo -t opinionated -p npm`
The project scaffolded will contain two expressots dependencies, `@expressots/core` and `@expressots/adapter-express`
If you want to contribute to the core library just uninstall it from your scaffolded project.

Then, inside of the @expressots/core, after building and generating the ./lib just type `npm pack` to generate a local library in which you can install it in your scaffolded project. Thats one strategy for you to modify and test your changes in the core.

I hope it helps. Also, I would recommend you to read the doc for you to get involved with the project philosophy. Take in the current tasks we have in the board as well. [Project Board](https://github.com/orgs/expressots/projects/5)

Looking forward to see your contributions

**Comment by mohanadft** [comment]
Heloo @rsaz 

Thank you for the guide, it really helped me.
Moreover, do you recommend any resources out there? I am pretty good at Node/Express but if there is something I should know to have a clear understanding, pleas let me know.
