### ISSUE TITLE
feat: Global Error Handler and Response envelope as middleware

### ISSUE THREAD

**Issue by shravan20** [expressots/expressots#110]
### Is there an existing proposal similar to this?

- [X] I have searched the existing proposals

### What are you proposing?

**_Proposal Description_**:

- Implement a custom middleware for handling the Error handling at the global level and also add response handler as well based on the use case of the API.
- Currently, we have to make custom middlewares as part of the user defined middlewares. This change would ensure that framework itself provides with a custom handler and people can simply override it and add custom handler as per their requirements.

### Is there any specific group of users that will benefit from this?

NA

### What problems are you trying to solve?

Problems resolved:
- Creating custom error handler and response handler
- Generalization of response envelope and error response wrapper

### Do you have any references or examples that can illustrate your idea?

This [implementation](https://github.com/shravan20/the.internet.folks/blob/main/src/middlewares/response.middleware.js) is JS version implemented in express.js framework, similar bit can be added in expressots as default or optional behavior internally. 

### What type of idea is this?

Innovation: No similar idea exists

**Comment by shravan20** [comment]
@rsaz: In case we plan to do this in expressots, can you please assign this to me?

**Comment by rsaz** [comment]
Hi @shravan20 we already have that built-in in the framework. When you scaffold a new project, the application provider adds a default global error handler that returns a json with error code and error message. See the code below:

Another cool feature that we add was, in the same method you can override the the default error handler if you will just passing your new error handler middleware like so:

```typescript
const yourErrorHandler = (req, res, next) => {
    console.log("testing your error handler");
    next();
}
```

Setting your custom error handler:
```typescript
this.middleware.setErrorHandler(yourErrorHandler);
```

```typescript
@provide(App)
export class App extends AppExpress {
    private middleware: IMiddleware;
    private provider: IProvider;

    constructor() {
        super();
        this.middleware = container.get<IMiddleware>(Middleware);
        this.provider = container.get<IProvider>(Provider);
    }

    protected configureServices(): void {
        this.middleware.addBodyParser();
        this.middleware.setErrorHandler();
    }

    protected postServerInitialization(): void {
        if (this.isDevelopment()) {
            this.provider.envValidator.checkAll();
        }
    }

    protected serverShutdown(): void {}
}
```

**Comment by rsaz** [comment]
@shravan20 closing the issue as it is responded in the message above.
