### ISSUE TITLE
Linter is not working until we setup the husky

### ISSUE THREAD

**Issue by shravan20** [expressots/expressots#121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Currently, without execution of npm run prepare, we see that husky for the project is not auto setup. This basically an additional setup for the developer after installation, which might be missed most of the time.

### Steps to reproduce

1. Clone the code
2. npm install
3. start working and make commits, you would pre commit hooks are not working

### Expected behavior

Ideally pre commit hooks should be setup as soon as project setup is done automatically without causing any overhead for developer to set it up.

### Package version

@expressots/*

### Node.js version

@expressots/*

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Other

Solution:

Add a script in package.json:
```
...
"postinstall": "npm run prepare"
...
```

This ensures that the pre commit hooks is auto setup after completion of the `npm install`

**Comment by shravan20** [comment]
@rsaz: Please assign this to me, since this is a very minor fix.

**Comment by rsaz** [comment]
Closed in the PR #122
