### ISSUE TITLE
Implement Unit test for Core

### ISSUE THREAD

**Issue by Amorim33** [expressots/expressots#128]
## Description

Add unit tests in all modules.

Current Modules:

- application: app-container, app-factory
- common: color-service, package-resolver, project-config
- console: console
- container-module
- controller: base-controller
- decorator: scope-binding
- error: app-error, error-handler-middleware, report, status-code
- middleware: middleware-resolver, middleware-service
- provider: provider-manager, db-in-memory, dto-validator, env-validator, logger
- render

## Suggested Pattern

- Inside of every module, add all unit tests in a folder called `__tests__`.
- Unit test file names should have the suffix `.spec`

![Image](https://user-images.githubusercontent.com/42624869/265867754-a0f10dd6-d20e-482c-8834-10b9758682a0.png)

## Requirements

- [ ] all features must have tests;
- [ ] code coverage must pass.

**Comment by rsaz** [comment]
PR #127 completed.

**Comment by rsaz** [comment]
- Missing application.spec.ts
And the other modules:
- container-module
- controller
- decorator
- error
- middleware
- provider
- render
