### ISSUE TITLE
Bodyparsers entity large

### ISSUE THREAD

**Issue by ArielBetti** [expressots/expressots#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Big payload cause bug entity large in body-parser

### Expected behavior

{
  "_id": "gengar",
  "logs": [
    "a",
    "b"
  ],
  "userName": "asancodigos",
  "_playerId": "x",
  "winner": false,
  "pokemon1": "444beaed-f246-4011-a36a-257370055586",
  "pokemon2": "pikachu"
}

### Package version

1.2.0

### Node.js version

18.13.0

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by rsaz** [comment]
Hi @ArielBetti , the next release will be happening this week and together with the release will come the fix for this issue reported.

**Comment by rsaz** [comment]
The issue with the payload too large has been resolved, so I'm closing it. You can update to the new core version 1.2.1 here: https://www.npmjs.com/package/@expressots/core?activeTab=readme

The body parser still comes as a default provided by ExpressoTS, with a limit of 100KB, which is the default set in express.json().

If you need larger payloads, simply add the middleware in the main function:

```Typescript
async function Bootstrap() {
    const app = App.create(container, [express.json({limit: "set the desired limit"})]);
    app.listen(
        ENV.Application.PORT,
        ServerEnvironment[ENV.Application.ENVIRONMENT],
        {
            appName: ENV.Application.APP_NAME,
            appVersion: ENV.Application.APP_VERSION,
        },
    );
}
```
Every time you are going to work with larger payloads, greater than the base 100KB, which is quite substantial, make sure you import the compress package into your project to help with compression and reduce the payload size on the network.
