### ISSUE TITLE
Node.js v20.12.2 is not supported

### ISSUE THREAD

**Issue by pyr3-dev** [expressots/expressots#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

it doesn't let me use latest node version to create a new expressots project

### Steps to reproduce

1. mkdir expressots
2. cd expressots
3. npm i -g @expressots/cli
4. expressots new exprossots  -p npm -t opinionated

### Expected behavior

make the scaffold project

### Package version

@expressots/cli@1.8.2

### Node.js version

v20.12.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

i use npm

**Comment by rsaz** [comment]
Hi @pyr3-dev the next version will come by the end of this week which includes removing this lock in version. We are testing at the moment to avoid any conflict with inversify and deprecated function signatures from previous nodejs version. I will be updating this ticket once we release the new version.
