### ISSUE TITLE
CLI opinionated - user use-cases should return NotFound, not BadRequest

### ISSUE THREAD

**Issue by acroyear** [expressots/expressots#39]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Reading the source code of opinionated, I found i had an opinionated bit of feedback. :)

The headers for not finding the user in Find, Update, Delete all return 400 Bad Request when the user isn't in the db. They should return 404 to follow the http standard.

### Describe the feature you'd like

Standard REST header for an endpoint not finding the asset being requested (presuming this isn't a search) is to return 404 NotFound.  400 BadRequest should be reserved for cases where the parameters of a query are actually incorrect to the data or the endpoint (e.g., if your id's were numbers (db sequence id's) and the user sent a request for id of Fred).

Create is fine with a 400 when the inputs are incorrect. The Find, Update, and Delete are the ones I'd suggest to update.

### Teachability, documentation, adoption, migration strategy

Just setting a good example for using the HTTP headers properly.

### What is the motivation / use case for changing the behavior?

Just setting a good example for using the HTTP headers properly.

**Comment by rsaz** [comment]
Hi @acroyear good suggestion.

Request completed. #41
