### ISSUE TITLE
E2E integration test with Jest: no way to manually stop http server 

### ISSUE THREAD

**Issue by edesdan** [expressots/expressots#504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I was dealing with this for a few days and I think there is an issue with this. I was following your guid for [testing](https://doc.expresso-ts.com/docs/features/test) (E2E testing with supertest) and I notice that the example provided initialise the underline server with listen but await appInstance.getHttpServer() return an object on which is not possible to call .stop() to stop web server. This means that basically the test leave the server running after test is completed and jest won't terminate. 

Here is my code:

```
import "reflect-metadata";

import { AppFactory, ServerEnvironment, StatusCode } from "@expressots/core";
import { container } from "../../../src/app.container";
import { App } from "../../../src/providers/app/app.provider";
import express from "express";
import request from "supertest";


describe("health check api", () => {
    let server:express.Application;

    beforeAll(async () => {
        await startHttpServerOnRandomPort();
    });

    afterAll(async () => {
        //await server.close() we cannot close the server due to framework limitation?
    });

    async function startHttpServerOnRandomPort() {
        const appInstance = await AppFactory.create(container, App);
        await appInstance.listen(0, ServerEnvironment.Development); //we create a server every time on random port, it could be changed when we can manually stop the server (see afterAll)
        server = await appInstance.getHttpServer();
    }

    describe("Should call health check endpoint and return 200 OK", () => {
        test("GET /health", async () => {

            const expectedResponseBody = {
                health: "OK",
            };

            const response = await request(server).get("/health");

            expect(response.status).toBe(StatusCode.OK);
            expect(response.body).toEqual(expectedResponseBody);
        });
    });
});
```

Any idea what's wrong here? 

### Expected behavior

Expected: a way to manually stop()/cleanup server in afterAll method:

`    afterAll(async () => {
        await server.close() 
    });`

### Package version

1.2.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [X] Linux

### Other

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.8 s, estimated 1 s
Ran all test suites.
Jest did not exit one second after the test run has completed.

'This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

**Comment by edesdan** [comment]
ah, I am very glad to hear that! 

I tried the other route you suggested already but it was looking like a workaround and there were other issues with that.

One thing also to consider in my opinion is the ability to start the server on a random available port, usually if you pass '0' as port the server starts on a random available port that is very handy for e2e testing. I am not sure if nodejs allow this or not but I think this would be a nice addition to what you already have there.  

Looking forward to try 3.0.0 and nice job for the framework, it is very cool imo!

**Comment by rsaz** [comment]
> ah, I am very glad to hear that!
> 
> I tried the other route you suggested already but it was looking like a workaround and there were other issues with that.
> 
> One thing also to consider in my opinion is the ability to start the server on a random available port, usually if you pass '0' as port the server starts on a random available port that is very handy for e2e testing. I am not sure if nodejs allow this or not but I think this would be a nice addition to what you already have there. In my previous example there I wanted to do that but in reality what's happening there is that if I pass 0 the server starts on port 3000 as default...
> 
> Looking forward to try 3.0.0 and nice job for the framework, it is very cool imo!


Thank you for your kind words! Lots of inspirations from SpringBoot, .Net and some others.

This is a good idea and easy to implement. I might implement this to incorporate in the v3.0.0.

Currently, we offer the method `close()` from the adapter-express directly, as more requests are coming from devs to have access to the http server underneath, what I might do is:

```ts
interface IHttpServer {
   close(enableLog?: boolean): Promise<void>;
   get Port(): number;
}
```

`app.listen(): Promise<IHttpServer>` I might return the server on `app.listen()` method, so I can create an interface to tailor what I want to allow the dev to have access to, to avoid breaking the application flow, and any new request I can just add to that interface.

It will looks like this:

```ts
app.listen("your port");
app.listen(); // assign random port
app.listen(0); // assign random port

const server = app.listen(0);

server.close();
server.Port
```

**Comment by edesdan** [comment]
Yes but app.listen atm is also starting the server on the specific port. 

Ideally I'd like to do this:

```
 const appInstance = await AppFactory.create(container, App);
 await appInstance.listen(0, ServerEnvironment.Development); // pass 0 to listen on random port
```

and later on:

`appInstance.stop()`

Then if we already have 
` appInstance.getHttpServer()`

this method should actually return the underline httpServer.

This is was also what I was expecting by appInstance.getHttpServer() (to return the underline webserver object) but in reality is returning something else so also the doc was kind of misleading. 

Not sure if that makes sense

**Comment by rsaz** [comment]
Hi @edesdan `npm i @expressots/cli@3.0.0-beta.4` is out, try it!

It resolves the 2 issues referred in this ticket:

1- returning the underline http server which you can call `close()` method

```ts
import request from "supertest";

import { AppFactory, StatusCode } from "@expressots/core";
import { IWebServerBuilder } from "@expressots/shared";

import { Server } from "http";
import { App } from "../src/app";

describe("AppController", () => {
    let server: Server;
    let webServerBuilder: IWebServerBuilder;

    beforeAll(async () => {
        webServerBuilder = await AppFactory.create(App);
        const app = await webServerBuilder.listen(3000);
        server = await app.getHttpServer();
    });

    afterAll(async () => {
        await server.close();
    });

    it("returns a valid AppResponse", async () => {
        return request(server)
            .get("/v1")
            .expect(StatusCode.OK)
            .expect("Hello from ExpressoTS!");
    });
});
```

2 - Now you can pass 0 in the `listen()` method and the server will assign any available port in your OS randomly.

```ts
AppFactory.create(App).then((app) =>
    app.listen(0, {
        appName: env.App.appName,
        appVersion: env.App.appVersion,
    }),
);
```
![image](https://github.com/user-attachments/assets/953a1eff-1283-43e8-ac26-32351772171f)

**Comment by edesdan** [comment]
Oh, that's nice, thanks for the quick turn around! 

I am having some issues upgrading to 3.x now, is there like a migration guide from 2.x? It looks like there are few breakable/structural changes..

**Comment by edesdan** [comment]
ah nice! I think I managed to upgrade but I am left with the error above? Can you help me? Am I doing something wrong?

I am following the guide but I get this:

```
src/app.ts:11:15 - error TS2416: Property 'globalConfiguration' in type 'App' is not assignable to the same property in base type 'AppExpress'.
  Type '() => void | Promise<void>' is not assignable to type '() => Promise<void>'.
    Type 'void | Promise<void>' is not assignable to type 'Promise<void>'.
      Type 'void' is not assignable to type 'Promise<void>'.

11     protected globalConfiguration(): void | Promise<void> {
```

**Comment by rsaz** [comment]
> ah nice! I think I managed to upgrade but I am left with the error above. Can you help me? Am I doing something wrong?
> 
> I am following the guide but I get this error:
> 
> ```
> src/app.ts:11:15 - error TS2416: Property 'globalConfiguration' in type 'App' is not assignable to the same property in base type 'AppExpress'.
>   Type '() => void | Promise<void>' is not assignable to type '() => Promise<void>'.
>     Type 'void | Promise<void>' is not assignable to type 'Promise<void>'.
>       Type 'void' is not assignable to type 'Promise<void>'.
> 
> 11     protected globalConfiguration(): void | Promise<void> {
> ```

All life cycle hooks in the `app.ts` file are now async, please change the `globalConfiguraion`, `configureServices`, `postServerInitialization` and `serverShutdown` to async and Promise<void> as follow:

```ts
import { AppExpress } from "@expressots/adapter-express";
import { AppContainer, Env } from "@expressots/core";
import { AppModule } from "@useCases/app/app.module";

export class App extends AppExpress {
    private config: AppContainer = this.configContainer([AppModule]);

    async globalConfiguration(): Promise<void> {}

    async configureServices(): Promise<void> {}

    async postServerInitialization(): Promise<void> {}
     
    async serverShutdown(): Promise<void> {}
```

Here is the comprehensive guide to migrate from 2.x to 3.x : https://doc.expresso-ts.com/docs/prologue/upgrade_guide

Version 3.0 is coming out tomorrow if all tests running tonight are green. We will be announcing in our discord and [LinkedIn](https://www.linkedin.com/company/expresso-ts/?viewAsMember=true) soon.

**Comment by edesdan** [comment]
ok that's very good news. I managed to upgrade but I've got 2 issues now:


1. listening on random port doesn't seems to work:

```
 async function startHttpServer() {

        webServerBuilder = await AppFactory.create(App);
        const app = await webServerBuilder.listen(0, {
            appName: env.Application.APP_NAME,
            appVersion: env.Application.APP_VERSION,
        });

        server = await app.getHttpServer();
    }
```

I get this:

![Screenshot 2024-12-04 at 09 07 06](https://github.com/user-attachments/assets/17d7a882-796b-4e81-9dc5-6df4df90ae63)

2. running npm run dev gives me following error on cli:

```
npm run dev
(node:32061) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

> trip-manager-html-to-pdf@1.0.0 dev
> expressots dev


🐎 Expressots

/bin/sh: tsx: command not found
/Users/daniele.desanctis/repositories/travelport/trip-manager-html-to-pdf/node_modules/@expressots/cli/bin/commands/project.commands.js:137
                reject(new Error(`Command failed with code ${code}`));
                       ^
Error: Command failed with code 127
    at ChildProcess.<anonymous> (/Users/daniele.desanctis/repositories/travelport/trip-manager-html-to-pdf/node_modules/@expressots/cli/bin/commands/project.commands.js:137:24)
    at ChildProcess.emit (node:events:507:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1101:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

**Comment by rsaz** [comment]
Few things for you to confirm:

1 - make sure you have install the cli `@expressots/cli@3.0.0-beta.4` in the npm global
```bash
npm i @expressots/cli@3.0.0-beta.4 -g
```
2 - Make sure all deps are correct

```json
"dependencies": {
    "@expressots/adapter-express": "3.0.0-beta.4.2",
    "@expressots/core": "3.0.0-beta.4",
    "@expressots/shared": "3.0.0-beta.4"
  },
  "devDependencies": {
    "@expressots/cli": "3.0.0-beta.4",
    "@types/express": "5.0.0",
    "@types/jest": "29.5.14",
    "@types/node": "20.12.7",
    "@typescript-eslint/eslint-plugin": "8.0.0",
    "@typescript-eslint/parser": "8.0.0",
    "eslint": "8.57.0",
    "eslint-config-prettier": "9.0.0",
    "eslint-plugin-prettier": "5.0.0",
    "jest": "29.7.0",
    "prettier": "3.2.5",
    "supertest": "^7.0.0",
    "ts-jest": "29.1.2",
    "tsconfig-paths": "4.2.0",
    "tsx": "4.19.2",
    "typescript": "5.1.3"
  }
```
3 - make sure expressots.config is correct configured for the new version

```ts
import { ExpressoConfig, Pattern } from "@expressots/shared";

const config: ExpressoConfig = {
    entryPoint: "main",
    sourceRoot: "src",
    scaffoldPattern: Pattern.KEBAB_CASE,
    opinionated: true,
};

export default config;
```
4 - to avoid any conflict with previous installation, as you migrated your project, make sure you:
4.1 - remove node_modules and package-lock.json
```bash
rm node_modules
rm package-lock.json
```
This will remove any cache and clean your npm install locally

5 - now make sure you install everything : 
```bash
npm i
```

6 - execute your command `npm run dev`

Obs: make sure that your "devDependencies": { "@expressots/cli": "3.0.0-beta.4" } is there. This is the most common mistake on migrating.

Other than that, read carefully the migration doc and you should be good to go.

**Comment by edesdan** [comment]
ok so I followed your guide and the issue with server running on random port was solved by adding 

`    "@expressots/adapter-express": "3.0.0-beta.4.2"`

previously I only had `3.0.0-beta.4`. The nice thing is that is now working. Thanks!

The issue running  `npm run dev` is still there. I cannot run the app atm.

**Comment by edesdan** [comment]
I found out that I need this to be installed otherwise I can't `run npm run dev`:

`npm install -g tsx`

but I am not sure why as before I didn't need to do that I think. Shouldn't this been installed as dependency somehow?

**Comment by rsaz** [comment]
> I found out that I need this to be installed otherwise I can't `run npm run dev`:
> 
> `npm install -g tsx`
> 
> but I am not sure why as before I didn't need to do that I think. Shouldn't this been installed as dependency somehow?

`tsx` is used for executing the application. It is listed in the previous message as a dev dependency of your project. Its also part of the migration doc. You don't need to install globally if you don't want to.

I am closing this ticket as the initial issue related to E2E testing was resolved. Any other new problem please open a new ticket.

Thank you @edesdan
