### ISSUE TITLE
Ability to configure different .envs files

### ISSUE THREAD

**Issue by edesdan** [expressots/expressots#507]
### Is there an existing proposal similar to this?

- [X] I have searched the existing proposals

### What are you proposing?

Not sure if this is something you are already considering for v3.0 but basically the idea is to have different .env files to distinguish between different envs. 

At the moment not sure how to do that really (the documentation is not clear on this). What I would like to have is a way to have different .envs files:

```
.env.local
.env.development
.env.preprod
.env.prod

```
for example and a way to tell espresso that I am building my app for a specific env (so to consider the env variables from that specific file). This is essential for deployment and also for local testing.

Ideally it would be good to pass something like this:

`expressots run "development"` where development is the env for the .env filename.

Not sure if this makes sense.

### Is there any specific group of users that will benefit from this?

Everybody can benefit from this

### What problems are you trying to solve?

 tell espresso that I am building my app for a specific env (so to consider the env variables from that specific file)

### Do you have any references or examples that can illustrate your idea?

similar concept in springboot (profile/env management)

### What type of idea is this?

Innovation: No similar idea exists

**Comment by rsaz** [comment]
The `v3.0.0` is about to be released can be accesses by `npm i @expressots/cli@3.0.0-beta.4` and includes this functionality of having multiple .env files. We will be updating the doc shortly but you can see an example in the opinionated template and below

```ts
async globalConfiguration(): Promise<void> {
        this.setGlobalRoutePrefix("/v1");

        this.initEnvironment("development", {
            env: {
                development: ".env.development",
                production: ".env.production",
            },
        });
    }
```

![image](https://github.com/user-attachments/assets/3a69c636-3cd9-49f7-a4b0-8cc867326354)
