### ISSUE TITLE
Unable to inject dependency on Application

### ISSUE THREAD

**Issue by AntonyZ89** [expressots/expressots#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Created a provider called "EventManager" and tried inject it on Application class to be invoked on `postServerInitialization()`

<img width="485" alt="2023-07-25_14-50" src="https://github.com/expressots/expressots/assets/1340674/5668df62-b085-4d90-99d3-e841046c7ebb">

But received this error on start the server:

<img width="485" alt="2023-07-25_14-50" src="https://github.com/expressots/expressots/assets/1340674/618f3dfa-68e0-46bb-a499-7474a65b9c74">

### Steps to reproduce

1. `npm ci`
2. `npm run dev`

### Expected behavior

<img width="485" alt="2023-07-25_14-50" src="https://github.com/expressots/expressots/assets/1340674/a07ef1b9-ce62-4871-be99-ee78a11d2cda">

### Package version

1.5.1

### Node.js version

18.14.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

[di-issue.zip](https://github.com/expressots/expressots/files/12164824/di-issue.zip)

**Comment by AntonyZ89** [comment]
After read the doc of Inversify I solved this problem doing the following changes:

`application.provider.ts`
```typescript
const appInstance = new App();

export { appInstance as App };
``` 
to
```typescript
export { App };
``` 

--

`src/main.ts`
```typescript
const app = App.create(container);
``` 
to
```typescript
const app = container.get(App);

app.create(container);
``` 

And it's works as expected:
<img width="485" alt="2023-07-25_14-50" src="https://github.com/expressots/expressots/assets/1340674/37df37bf-e5a3-4fae-802d-7887f22a2926">

Opened this issue because I believe it is a problem in the template as it does not accept injecting dependency into the Application class.

**Comment by rsaz** [comment]
Hi @AntonyZ89 to resolve this issue in the proper manner I would recommend you to do this instead:

```typescript
@provide(TwitchProvider)
class TwitchProvider {
    async getAuthProvider(): Promise<string> {
        return randomUUID();
    }
}

export { TwitchProvider };
```

Use the container to request services, instances like the code below:

```typescript
@provide(App)
class App extends Application {
    private twitchProvider: TwitchProvider;

    constructor() {
        super();
        this.twitchProvider = container.get<TwitchProvider>(TwitchProvider);
    }

    protected configureServices(): void {
        Environments.checkAll();
    }

    // eslint-disable-next-line @typescript-eslint/no-empty-function
    protected postServerInitialization(): void {
        console.log(this.twitchProvider.getAuthProvider());
    }

    protected serverShutdown(): void {
        log(LogLevel.Info, "Server is shutting down", "logger-provider");
        super.serverShutdown();
    }
}

const appInstance = new App();

export { appInstance as App };
```

This is a very similar approach to .NET core on requesting services from the DI system, and how we are using at the moment on ExpressoTS

```csharp
serviceProvider.GetRequiredService<SERVICES.Core.IAuthService>();
```

Let me know if it is working fine for you, so that I can close this ticket.

**Comment by AntonyZ89** [comment]
@rsaz Thanks, it works!
