### ISSUE TITLE
Website ChunkLoadErrors

### ISSUE THREAD

**Issue by michahell** [expressots/expressots#81]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

website is extremely slow due to ChunkLoadErrors
Did not seem to be caused by privacy badger, which when activated does throw some errors:

**With privacy badger on by default:**
<img width="1440" alt="Screenshot 2023-08-30 at 23 36 49" src="https://github.com/expressots/expressots/assets/225784/14e2b6a2-5b16-4523-a712-2ab039a69f32">
<img width="1440" alt="Screenshot 2023-08-30 at 23 36 41" src="https://github.com/expressots/expressots/assets/225784/ddc5b87c-6ec3-41e1-a51c-a0afbbd7203f">

**privacy badger off:**
<img width="1440" alt="Screenshot 2023-08-30 at 23 37 25" src="https://github.com/expressots/expressots/assets/225784/0e651e57-4806-4b58-82fd-5e835ccede8d">

<img width="432" alt="Screenshot 2023-08-30 at 23 36 59" src="https://github.com/expressots/expressots/assets/225784/0f88a7d9-78ad-41e0-8722-9e33659af969">

### Steps to reproduce

go to website

### Expected behavior

fast website!

### Package version

-

### Node.js version

-

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Other

mac OSX Big Sur 11.7.8 / chrome@Version 114.0.5735.198 (Official Build) (x86_64)

**Comment by ArielBetti** [comment]
I am investigating. At the beginning of the website, we had some issues related to Next.js that were affecting the site's performance. These problems have been resolved, and on Windows 11, using all browsers, I do not notice any slowness or similar issues. I tested it on an Intel-based MacBook Pro and noticed a slightly slower performance, but nothing too far from normal.

Can you provide more information about your device and browser?

May I ask you to perform one more test? Open the website with the window resized to the smallest possible size. This will prevent our code playground from opening, and it might help determine if the issue could be related to the StackBlitz SDK.

**Comment by rsaz** [comment]
Hi @michahell StackBlitz issues were resolved. Also for lack of feedback and interaction in this issue, and no complains for any other user, we are closing it the issue.

Thank you. Any other problem let us know.
